Added open and close methods for select, filterable select and autocomplete
primait/pyxis-components pull request #65
Opened 2020-09-07 13:18 UTC by VitalyOlegovic

New functions to allow to show and hide the available options in the select, filterable select and autocomplete components.

2020-09-07 13:48 UTC, alessiosantangelo requested changes
Solo una cavolatina su dove esporre le funzioni nei docs, poi il resto è ok ;)

2020-09-07 13:48 UTC, alessiosantangelo commented on src/Prima/Pyxis/Form/Autocomplete.elm
> +@docs autocomplete, init, update, autocompleteChoice, open, close
Li sposterei sotto `##  Methods`, dato che non sono metodi per la config iniziale.

2020-09-07 13:48 UTC, alessiosantangelo commented on src/Prima/Pyxis/Form/FilterableSelect.elm
> +@docs filterableSelect, init, update, filterableSelectChoice, open, close
Idem

2020-09-07 14:44 UTC, alessiosantangelo submitted a review, later dismissed

2020-09-07 16:41 UTC, kioan000 requested changes
- Aggiungerei anche una funzione `isOpen` per interrogare lo stato attuale visto che non è esposto.
- Per completezza aggiungerei un metodo `toggle`
- Chiamerei le funzioni open/close/toggleMenu, anche per concordanza con il nome che ha sullo StateConfig

2020-09-08 08:36 UTC, VitalyOlegovic commented
Creare una funzione `isMenuOpen` comporta un name clash. Si può chiamarla `isOpen`?

2020-09-08 09:18 UTC, alessiosantangelo requested changes

2020-09-08 09:18 UTC, alessiosantangelo commented on src/Prima/Pyxis/Form/Autocomplete.elm
> +    state
qui puoi fare direttamente `state.isMenuOpen`

2020-09-08 09:18 UTC, alessiosantangelo commented on src/Prima/Pyxis/Form/Select.elm
> +    state
Anche qui

2020-09-08 09:22 UTC, alessiosantangelo approved these changes
LGTM

2020-09-08 09:53 UTC, kioan000 requested changes
scegli una delle due nomenclature. 
open**Menu**, close**Menu** e toggle**Menu** oppure open, close, toggle

2020-09-08 10:00 UTC, kioan000 approved these changes
❤️

2020-09-10 08:19 UTC, merged