tolto evento in caso di clic su label o valore già selezionato
primait/pyxis-components pull request #82
Opened 2020-11-27 14:13 UTC by matteosister

Abbiamo notato che per i componenti del form Radio e RadioFlag, veniva lanciato l'evento di update anche se in realtà era stato cliccato lo stesso valore selezionato precendetemente.

Credo il problema sia solo con questi due, perchè la select si comporta correttamente di suo (il browser non lancia eventi).

2020-11-27 14:18 UTC, alessiosantangelo approved these changes

2020-11-30 08:18 UTC, damjack requested changes
Mi sembra manchi il componente `RadioButton` 😉 . Per il resto tutto ok

2020-11-30 17:05 UTC, Gsciarra reviewed
LGTM

2020-12-01 08:16 UTC, kioan000 approved these changes

2020-12-01 08:30 UTC, damjack approved these changes

2020-12-01 08:56 UTC, merged