Check validation for Form fields
primait/pyxis-components pull request #84
Opened 2021-01-18 17:13 UTC by damjack

Changelog:
- Implementata la funzione `isPristine` per verificare se il valore corrente è un `Just _` o diverso dal `DefaultValue`

2021-01-19 15:11 UTC, riccardo16 submitted a review, later dismissed

2021-02-05 13:57 UTC, riccardo16 reviewed
ho un dubbio sul funzionamento del Indeterminate (type Default).
Magari prima veniva utilizzato, ma ora (che pare sia inutilizzato), potrebbe creare problemi nel caso non venga settato il `defaultvalue` con `Value any`, forse bisognerebbe rimuoverlo?

2021-02-24 10:19 UTC, alessiosantangelo submitted a review, later dismissed

2021-03-22 09:49 UTC, alessiosantangelo requested changes
Scriverei due righe nel changelog perchè questa è una breaking change rispetto al comportamento attualmente implementato. 

Vanno fatti testi di non regressione su Hutch e Domus prima del merge visto che si tocca il meccanismo alla base dei form.

2021-03-22 09:49 UTC, alessiosantangelo commented on src/Prima/Pyxis/Form/Date.elm
> +            Value (config.reader model) == options.defaultValue
Lo metterei direttamente dentro il `case`

2021-03-22 09:49 UTC, alessiosantangelo commented on src/Prima/Pyxis/Form/Input.elm
> +    case ( sameDefault, config.reader model ) of
Lo metterei direttamente dentro il `case`

2021-03-22 09:49 UTC, alessiosantangelo commented on src/Prima/Pyxis/Form/Select.elm
> +    case ( sameDefault, stateConfig.selected ) of
`sameDefault` direttamente nel `case`

2021-03-22 09:49 UTC, alessiosantangelo commented on src/Prima/Pyxis/Form/TextArea.elm
> +    case ( sameDefault, config.reader model ) of
`sameDefault` direttamente nel `case`

2021-03-22 13:01 UTC, riccardo16 submitted a review, later dismissed

2021-03-24 08:21 UTC, damjack commented
> Scriverei due righe nel changelog perchè questa è una breaking change rispetto al comportamento attualmente implementato.
> 
> Vanno fatti testi di non regressione su Hutch e Domus prima del merge visto che si tocca il meccanismo alla base dei form.

La nuova opzione non comporta nessuna rottura dal funzionamento attuale proprio perché di default viene passato sempre `True`. Riguardiamola assieme in caso se hai dubbi

2021-03-24 08:21 UTC, alessiosantangelo submitted a review, later dismissed

2021-03-31 10:25 UTC, Emulator000 approved these changes

2021-03-31 10:29 UTC, merged