[PRIMA-9446]: L'attributo `for` delle label non contiene l'id dell'input a cui fanno riferimento.
primait/pyxis-components pull request #96
Opened 2021-07-19 12:33 UTC by lucbarn

https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/PRIMA-9446

2021-07-19 15:45 UTC, alessiosantangelo requested changes

2021-07-19 15:45 UTC, alessiosantangelo commented on src/Prima/Pyxis/Form/Checkbox.elm
> +composeIdBlocks : String -> String -> String
Non mi convince troppo `composeIdBlocks` come nome. Inoltre la desinenza `blocks` da l'idea di qualcosa che si riferisce ad una lista. 
Propongo un semplice `toCheckboxId` o `toId`

2021-07-19 15:45 UTC, alessiosantangelo commented on src/Prima/Pyxis/Form/Checkbox.elm
> +                |> Maybe.withDefault identity
Questa funzione potrebbe stare negli `Helpers`. O addirittura, meglio ancora, nel tipo `Label` con un'api del tipo `withConditionallyFor` o `withForIf`

2021-07-20 13:33 UTC, alessiosantangelo approved these changes

2021-07-20 14:24 UTC, Gsciarra approved these changes

2021-07-22 09:10 UTC, merged